// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdEhg0NjvHHK2BJK-iEREm1Fn1MRY78rw',
    appId: '1:181771474819:web:a87ebda5a9f3b9df01c8b6',
    messagingSenderId: '181771474819',
    projectId: 'fir-storeproject-19612',
    authDomain: 'fir-storeproject-19612.firebaseapp.com',
    storageBucket: 'fir-storeproject-19612.appspot.com',
    measurementId: 'G-XD4W1VMJ0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXn4k3PCcmTeNGdiDGKZyYo68iDRosdx8',
    appId: '1:181771474819:android:974bcc3b397f416d01c8b6',
    messagingSenderId: '181771474819',
    projectId: 'fir-storeproject-19612',
    storageBucket: 'fir-storeproject-19612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKit0OMuOp5fsk3N3jJ-u52a7lTy0H0hs',
    appId: '1:181771474819:ios:5bc7f298c4989a0a01c8b6',
    messagingSenderId: '181771474819',
    projectId: 'fir-storeproject-19612',
    storageBucket: 'fir-storeproject-19612.appspot.com',
    iosBundleId: 'com.example.firebaseProjectStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKit0OMuOp5fsk3N3jJ-u52a7lTy0H0hs',
    appId: '1:181771474819:ios:5bc7f298c4989a0a01c8b6',
    messagingSenderId: '181771474819',
    projectId: 'fir-storeproject-19612',
    storageBucket: 'fir-storeproject-19612.appspot.com',
    iosBundleId: 'com.example.firebaseProjectStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdEhg0NjvHHK2BJK-iEREm1Fn1MRY78rw',
    appId: '1:181771474819:web:a1d36df6ea86fb5b01c8b6',
    messagingSenderId: '181771474819',
    projectId: 'fir-storeproject-19612',
    authDomain: 'fir-storeproject-19612.firebaseapp.com',
    storageBucket: 'fir-storeproject-19612.appspot.com',
    measurementId: 'G-D8ZMQJP4L4',
  );

}